"use client";

import { useCallback, useEffect, useState } from "react";

// Generated by `python -m src.tajweed.build` into public/quran/tajweed/.
// A word is a list of segments; segment texts join to the Qālūn word, so
// colouring never needs offsets or splits a letter from its marks.
export type Segment = [string] | [string, number[]];
export type Note = [word: number, rule: number, start: number, en: string, ar: string, wajh?: string[]];
export type TajweedAyah = { a: number; w: Segment[][]; n?: Note[] };
export type TajweedSurah = { v: string; s: number; ayahs: TajweedAyah[] };
export type TajweedGroup = { en: string; ar: string; light: string; dark: string };
export type TajweedRule = {
  group: string; level: "core" | "detail"; harakat: number[] | null; page: number | null; tag: string | null;
  en: string; ar: string; explain_en: string; explain_ar: string; wajh?: string[];
};
export type TopicHit = [surah: number, ayah: number, word: number, text: string, rule: string];
export type TajweedTopic = {
  id: string; page: number | null; rules: string[]; en: string; ar: string; summary_en: string; summary_ar: string;
  points: [string, string][]; total: number; found: TopicHit[];
};
export type TajweedRules = {
  v: string; riwayah: string; tariq: string; context: string; hafs_compared: boolean;
  source: { title_ar: string; publisher: string; edition: string; isbn: string };
  order: string[]; groups: Record<string, TajweedGroup>; rules: Record<string, TajweedRule>; counts: Record<string, number>;
  basmala: { w: Segment[][]; n: Note[] }; topics: TajweedTopic[];
  examples: Record<string, [surah: number, ayah: number, word: number, segments: Segment[]][]>;
};

const BASE = "/quran/tajweed";
const cache = new Map<string, Promise<unknown>>();
function load<T>(url: string): Promise<T> {
  if (!cache.has(url)) cache.set(url, fetch(url).then(r => { if (!r.ok) throw new Error(String(r.status)); return r.json(); })
    .catch(error => { cache.delete(url); throw error; }));
  return cache.get(url) as Promise<T>;
}
export const loadRules = () => load<TajweedRules>(`${BASE}/rules.json`);
export const loadSurah = (surah: number) => load<TajweedSurah>(`${BASE}/${String(surah).padStart(3, "0")}.json`);

/** Rules plus one surah's words, keyed by ayah. Each file loads once per page. */
export function useTajweed(surah: number | null) {
  const [rules, setRules] = useState<TajweedRules | null>(null);
  const [ayahs, setAyahs] = useState<{ surah: number; map: Map<number, TajweedAyah> } | null>(null);
  const [error, setError] = useState(false);
  useEffect(() => { loadRules().then(setRules).catch(() => setError(true)); }, []);
  useEffect(() => {
    if (!surah) return;
    let live = true;
    setError(false);
    loadSurah(surah).then(data => { if (live) setAyahs({ surah, map: new Map(data.ayahs.map(a => [a.a, a])) }); })
      .catch(() => { if (live) setError(true); });
    return () => { live = false; };
  }, [surah]);
  return { rules, ayahs: ayahs?.surah === surah ? ayahs.map : null, error };
}

export type TajweedSettings = { show: boolean; details: boolean; hidden: string[]; check: boolean };
const DEFAULTS: TajweedSettings = { show: false, details: false, hidden: [], check: false };
const KEY = "rattil.tajweed.v1";

/** Reader preferences; storage failures (private mode) fall back to defaults. */
export function useTajweedSettings() {
  const [settings, setSettings] = useState<TajweedSettings>(DEFAULTS);
  useEffect(() => {
    try { const saved = localStorage.getItem(KEY); if (saved) setSettings({ ...DEFAULTS, ...JSON.parse(saved) }); } catch { /* defaults */ }
  }, []);
  const update = useCallback((patch: Partial<TajweedSettings>) => setSettings(previous => {
    const next = { ...previous, ...patch };
    try { localStorage.setItem(KEY, JSON.stringify(next)); } catch { /* not persisted */ }
    return next;
  }), []);
  return [settings, update] as const;
}

/** Rule ids of a segment that the current filters show, strongest first. */
export function visibleRules(indexes: number[] | undefined, rules: TajweedRules, settings: TajweedSettings) {
  return (indexes || []).map(i => rules.order[i]).filter(id => {
    const rule = rules.rules[id];
    return rule && !settings.hidden.includes(rule.group) && (settings.details || rule.level === "core");
  });
}

export const wordText = (segments: Segment[]) => segments.map(s => s[0]).join("");

export function harakatLabel(rule: TajweedRule, lang: "en" | "ar") {
  if (!rule.harakat) return "";
  const counts = rule.harakat.map(n => lang === "ar" ? n.toLocaleString("ar") : String(n)).join(lang === "ar" ? " أو " : " or ");
  return lang === "ar" ? `${counts} حركات` : `${counts} counts`;
}

/** CSS custom properties for the colour groups, from the generated registry. */
export function groupStyle(rules: TajweedRules | null): Record<string, string> {
  const style: Record<string, string> = {};
  for (const [id, group] of Object.entries(rules?.groups || {})) style[`--tj-${id}`] = group.light;
  return style;
}
