"""Rule registry: names, colour groups, Qālūn counts and book references.

`page` is the page of the Libyan Awqaf curriculum (2nd ed. 2022) where the rule
is taught. `level` "core" rules are coloured by default; "detail" rules are
available behind the reader's "all details" switch. `tag` is the token the
tajweed model learns for rules whose realisation is audible (see targets.py).
Tokens follow the acoustic-driven design of "Evaluating Automatic Speech
Recognition" (Table 4.6): rules that sound alike share a token, rules without
an acoustic marker (idghām without ghunna, iẓhār) get none. Adapted to Qālūn:
munfaṣil is 2 or 4 for Qālūn so it gets no <mad>, and <tasheel>/<silah> are added.
"""

GROUPS = {
    "madd_necessary": {"en": "Necessary madd · 6", "ar": "مد لازم · ٦", "light": "#a3001e", "dark": "#ff7a8a"},
    "madd_connected": {"en": "Connected madd · Qālūn 4", "ar": "مد متصل · ٤ لقالون", "light": "#b3125f", "dark": "#f78fbf"},
    "madd_permitted": {"en": "Permitted madd · 2/4/6", "ar": "مد جائز · ٢/٤/٦", "light": "#a84300", "dark": "#ffa45c"},
    "madd_natural": {"en": "Natural madd · 2", "ar": "مد طبيعي · ٢", "light": "#7a5b00", "dark": "#e0c35a"},
    "nasal": {"en": "Ghunna · nasal sound, 2", "ar": "غنة · حركتان", "light": "#08703a", "dark": "#5ee08f"},
    "merge": {"en": "Merged / not pronounced", "ar": "إدغام وما لا يُلفظ", "light": "#767c85", "dark": "#9aa0aa"},
    "qalqala": {"en": "Qalqala · echo", "ar": "قلقلة", "light": "#00706a", "dark": "#3ed9c9"},
    "heavy": {"en": "Heavy letter · tafkhīm", "ar": "تفخيم", "light": "#3a2fa8", "dark": "#aab4ff"},
    "light": {"en": "Light letter · tarqīq", "ar": "ترقيق", "light": "#3d6f8f", "dark": "#93c5e6"},
    "clear": {"en": "Clear · iẓhār", "ar": "إظهار", "light": "#4b5a3a", "dark": "#b9c9a3"},
    "riwaya": {"en": "Qālūn riwāyah point", "ar": "من أصول رواية قالون", "light": "#7a1fbf", "dark": "#d9a8ff"},
}

# id: group, level, harakat, page, tag, en, ar, explain_en, explain_ar[, wajh]
_RULES = [
    # ── Madd (pp. 58-66, Qālūn pp. 90-92) ──────────────────────────────────
    ("madd_lazim", "madd_necessary", "core", [6], 63, "mad",
     "Necessary madd", "مد لازم كلمي",
     "A long vowel followed by a permanent sukūn or shadda in the same word. Hold it 6 counts.",
     "حرف مد بعده سكون أصلي أو حرف مشدد في الكلمة نفسها، يُمد ست حركات وصلًا ووقفًا."),
    ("madd_lazim_harfi", "madd_necessary", "core", [6], 64, "mad",
     "Necessary madd (opening letters)", "مد لازم حرفي",
     "An opening letter whose name has three letters with a long vowel in the middle (ل م ن ق ص س ك). 6 counts.",
     "حروف فواتح السور المجموعة في «نقص عسلكم» تُمد ست حركات."),
    ("madd_ayn", "madd_permitted", "core", [6, 4], 65, "mad",
     "ʿAyn in Kāf-Hā-Yā-ʿAyn-Ṣād / ʿAyn-Sīn-Qāf", "عين فاتحتي مريم والشورى",
     "The letter ʿayn here may be held 6 counts (preferred) or 4.",
     "يجوز فيها الإشباع والتوسط، والإشباع هو المقدم.", ["6 (preferred)", "4"]),
    ("madd_muttasil", "madd_connected", "core", [4], 90, "mad",
     "Connected madd", "مد متصل",
     "A long vowel followed by a hamza in the same word. Qālūn holds it 4 counts (tawassuṭ).",
     "حرف مد بعده همز في كلمة واحدة، ولقالون فيه التوسط أربع حركات."),
    ("madd_muttasil_waqf", "madd_connected", "core", [4, 6], 113, "mad",
     "Connected madd when stopping", "مد متصل موقوف عليه",
     "The word ends in hamza and you stop on it: 4 counts, or 6 because the stop strengthens the hamza.",
     "تطرّف الهمز ووُقف عليه بالسكون: التوسط والإشباع لتقوي الهمز بالسكون.", ["4", "6"]),
    ("madd_munfasil", "madd_permitted", "core", [2, 4], 91, None,
     "Separated madd", "مد منفصل",
     "A long vowel at the end of a word and a hamza at the start of the next. Qālūn: 2 counts (qaṣr) or 4 (tawassuṭ). Pick one and keep it.",
     "حرف مد آخر الكلمة والهمز أول الكلمة التالية، ولقالون فيه القصر والتوسط مع التزام الوجه المختار.", ["2 (qaṣr)", "4 (tawassuṭ)"]),
    ("madd_changed_hamza", "madd_permitted", "core", [4, 2], 98, None,
     "Madd before a changed hamza", "مد قبل همز مغيَّر",
     "The hamza after this long vowel is eased (tas-hīl). Qālūn: 4 counts (preferred, the hamza's trace remains) or 2.",
     "سُهّلت الهمزة بعد حرف المد، فيجوز التوسط وهو المقدم لبقاء أثر الهمز، ويجوز القصر.", ["4 (preferred)", "2"]),
    ("madd_arid", "madd_permitted", "core", [2, 4, 6], 62, None,
     "Madd for stopping", "مد عارض للسكون",
     "You stop on the last letter, so the long vowel before it may be held 2, 4 or 6 counts. Stay consistent.",
     "سكون عارض للوقف بعد حرف المد، يجوز فيه القصر والتوسط والإشباع على نسق واحد.", ["2", "4", "6"]),
    ("madd_lin", "madd_permitted", "core", [2, 4, 6], 63, None,
     "Līn madd when stopping", "مد اللين",
     "A sākin wāw or yā after a fatḥa, before the letter you stop on: 2, 4 or 6 counts. No lengthening when joining.",
     "واو أو ياء ساكنة بعد فتح قبل حرف موقوف عليه، يجوز فيه القصر والتوسط والإشباع، ولا مد فيه وصلًا."),
    ("madd_silah", "madd_natural", "core", [2], 87, "silah",
     "Ṣilah of the pronoun hā", "صلة هاء الكناية",
     "The small wāw/yā after this hā means you lengthen it to hū / hī for 2 counts when joining. Dropped when stopping.",
     "تُوصل هاء الضمير بواو أو ياء لفظية بين متحركين بمقدار حركتين، وتُحذف الصلة وقفًا."),
    ("madd_tabii", "madd_natural", "detail", [2], 58, None,
     "Natural madd", "مد طبيعي",
     "An ordinary long vowel (ā, ū, ī) with no hamza or sukūn after it. 2 counts.",
     "حرف مد ليس بعده همز ولا سكون، يُمد حركتين."),
    ("madd_badal", "madd_natural", "detail", [2], 92, None,
     "Badal madd · Qālūn 2", "مد البدل · قصر لقالون",
     "A hamza followed by a long vowel (ءَا، أُو، إِي). Qālūn keeps it at 2 counts (Warsh lengthens it).",
     "تقدّم الهمز على حرف المد، وليس لقالون فيه إلا القصر."),
    ("madd_iwad", "madd_natural", "detail", [2], 113, None,
     "Stopping on tanwīn fatḥ", "مد العوض",
     "When you stop here the -an becomes a long ā (2 counts).",
     "عند الوقف على تنوين الفتح يُبدل ألفًا تُمد حركتين."),
    ("madd_harfi_tabii", "madd_natural", "detail", [2], 65, None,
     "Opening letter, 2 counts", "مد حرفي طبيعي",
     "Opening letters whose names have two letters (ح ي ط ه ر) are held 2 counts.",
     "حروف «حي طهر» في فواتح السور تُمد حركتين."),
    ("wasl_drop", "merge", "core", None, 66, None,
     "Long vowel dropped when joining", "حرف مد يُحذف وصلًا",
     "A sākin letter follows in the next word, so this long vowel is read short when you join the words.",
     "إذا التقى حرف المد بساكن في الكلمة التالية حُذف لفظًا عند الوصل للتخلص من التقاء الساكنين."),
    # ── Nūn sākinah / tanwīn, mīm (pp. 46-53) ───────────────────────────────
    ("ghunna", "nasal", "core", [2], 51, "n_ghunna",
     "Ghunna", "غنة",
     "Nūn or mīm with shadda: hold the nasal sound 2 counts.",
     "النون والميم المشددتان تُظهر غنتهما بمقدار حركتين."),
    ("ikhfa", "nasal", "core", [2], 49, "n_ikhfa",
     "Ikhfāʾ (hidden nūn)", "إخفاء حقيقي",
     "Nūn sākinah or tanwīn before one of 15 letters: hide the n into a nasal sound for 2 counts, without shadda.",
     "النون الساكنة أو التنوين قبل أحد خمسة عشر حرفًا: نطق بين الإظهار والإدغام مع غنة حركتين."),
    ("iqlab", "nasal", "core", [2], 49, "m_ikhfa",
     "Iqlāb (n becomes m)", "إقلاب",
     "Nūn sākinah or tanwīn before bāʾ turns into a hidden mīm with ghunna, 2 counts.",
     "تُقلب النون الساكنة أو التنوين ميمًا مخفاة بغنة عند الباء."),
    ("idgham_ghunna", "nasal", "core", [2], 47, "idgham_ghunna",
     "Idghām with ghunna", "إدغام بغنة",
     "Nūn sākinah or tanwīn merges into the next word's ي ن م و, keeping the nasal sound 2 counts.",
     "تُدغم النون الساكنة أو التنوين في حروف «ينمو» من كلمتين مع الغنة."),
    ("ikhfa_shafawi", "nasal", "core", [2], 52, "m_ikhfa",
     "Lip ikhfāʾ", "إخفاء شفوي",
     "Mīm sākinah before bāʾ: close the lips lightly with ghunna, 2 counts. (With mīm al-jamʿ this is the sukūn way.)",
     "الميم الساكنة قبل الباء تُخفى بغنة. (في ميم الجمع هذا على وجه الإسكان.)"),
    ("idgham_shafawi", "nasal", "core", [2], 52, None,
     "Lip idghām", "إدغام شفوي (مثلين صغير)",
     "Mīm sākinah merges into the next mīm with ghunna, 2 counts.",
     "الميم الساكنة تُدغم في الميم بعدها مع إظهار الغنة."),
    ("idgham_no_ghunna", "merge", "core", None, 48, None,
     "Idghām without ghunna", "إدغام بغير غنة",
     "Nūn sākinah or tanwīn merges completely into lām or rāʾ. No nasal sound.",
     "تُدغم النون الساكنة أو التنوين في اللام والراء إدغامًا كاملًا بلا غنة."),
    ("izhar_halqi", "clear", "detail", None, 46, None,
     "Iẓhār (clear nūn)", "إظهار حلقي",
     "Nūn sākinah or tanwīn before a throat letter (ء ه ع ح غ خ): pronounce the n clearly.",
     "النون الساكنة أو التنوين قبل حروف الحلق تُظهر بلا غنة زائدة."),
    ("izhar_mutlaq", "clear", "detail", None, 48, None,
     "Absolute iẓhār", "إظهار مطلق",
     "Nūn before wāw/yā inside one word (الدنيا، بنيان، قنوان، صنوان) stays clear.",
     "النون قبل الواو أو الياء في كلمة واحدة تُظهر لئلا تلتبس الكلمة بغيرها."),
    ("izhar_shafawi", "clear", "detail", None, 52, None,
     "Clear mīm before wāw/fāʾ", "إظهار شفوي",
     "Keep this mīm sākinah fully clear; take special care before wāw and fāʾ.",
     "تُظهر الميم الساكنة، وأشد ما يكون الحرص عند الواو والفاء."),
    # ── Silent letters and assimilation (pp. 54-57) ──────────────────────────
    ("hamzat_wasl", "merge", "core", None, 66, None,
     "Hamzat al-waṣl", "همزة وصل",
     "Not pronounced when you join from the previous word. When you start here it is read as a hamza.",
     "تسقط في الدرج، ويُبتدأ بها عند الابتداء."),
    ("silent", "merge", "core", None, 117, None,
     "Written, not pronounced", "حرف يُكتب ولا يُلفظ",
     "Part of the Uthmānī spelling only; do not pronounce it.",
     "حرف ثابت في الرسم العثماني ساقط في اللفظ."),
    ("idgham_shamsi", "merge", "core", None, 54, None,
     "Sun-letter lām", "لام شمسية",
     "The lām of al- merges into the following doubled letter and is not pronounced.",
     "تُدغم لام التعريف في الحرف الشمسي بعدها فلا تُلفظ."),
    ("izhar_qamari", "clear", "detail", None, 54, None,
     "Moon-letter lām", "لام قمرية",
     "The lām of al- is pronounced clearly.",
     "تُظهر لام التعريف قبل الحروف القمرية."),
    ("idgham_harf", "merge", "core", None, 54, None,
     "Idghām of letters", "إدغام المتماثلين والمتجانسين والمتقاربين",
     "This sākin letter merges into the next (doubled) letter, which is read with shadda.",
     "يُدغم الحرف الساكن في الحرف المشدد بعده فيصيران حرفًا واحدًا مشددًا."),
    # ── Qalqala, tafkhīm and tarqīq (pp. 41-45) ──────────────────────────────
    ("qalqala", "qalqala", "core", None, 41, "qalqala",
     "Qalqala", "قلقلة",
     "ق ط ب ج د with sukūn: release it with a light echo, without adding a vowel.",
     "حروف «قطب جد» الساكنة يُنطق بها مع نبرة واهتزاز دون تحريك."),
    ("qalqala_waqf", "qalqala", "core", None, 41, "qalqala",
     "Qalqala when stopping", "قلقلة كبرى عند الوقف",
     "You stop on a qalqala letter, so its echo is strongest here.",
     "الوقف على حرف القلقلة يجعلها أوضح ما تكون."),
    ("ra_tafkhim", "heavy", "core", None, 44, None,
     "Heavy rāʾ", "راء مفخمة",
     "Read this rāʾ full and heavy.",
     "تُفخم الراء هنا بحسب حركتها أو ما قبلها."),
    ("ra_tarqiq", "light", "detail", None, 44, None,
     "Light rāʾ", "راء مرققة",
     "Read this rāʾ light (thin).",
     "تُرقق الراء هنا لكسرها أو لكسر ما قبلها أو لياء ساكنة قبلها."),
    ("ra_both", "heavy", "core", None, 45, None,
     "Rāʾ: both allowed", "راء فيها الوجهان",
     "Scholars allow this rāʾ heavy or light.",
     "يجوز في هذه الراء التفخيم والترقيق.", ["heavy", "light"]),
    ("lam_tafkhim", "heavy", "core", None, 43, None,
     "Heavy lām of Allāh", "تفخيم لام لفظ الجلالة",
     "After a fatḥa or ḍamma (or when you start here) the lām of Allāh is heavy.",
     "تُفخم لام لفظ الجلالة بعد فتح أو ضم أو عند الابتداء به."),
    ("lam_tarqiq", "light", "detail", None, 43, None,
     "Light lām of Allāh", "ترقيق لام لفظ الجلالة",
     "After a kasra the lām of Allāh is light.",
     "تُرقق لام لفظ الجلالة بعد كسر."),
    ("tafkhim_letter", "heavy", "detail", None, 43, None,
     "Always-heavy letter", "حرف استعلاء مفخم",
     "خ ص ض غ ط ق ظ are always heavy; ط ض ص ظ most of all.",
     "حروف «خص ضغط قظ» مفخمة دائمًا، وحروف الإطباق أقواها تفخيمًا."),
    # ── Qālūn riwāyah topics (chapter 3, pp. 75-124) ────────────────────────
    ("mim_jam", "riwaya", "detail", None, 85, None,
     "Mīm al-jamʿ", "ميم الجمع",
     "Qālūn has two ways before a voweled letter: sukūn (preferred) or ṣilah, read as -mū for 2 counts (2 or 4 before a hamza).",
     "لقالون فيها قبل المتحرك وجهان: الإسكان وهو المقدم في الأداء، والصلة بواو لفظية تُمد حركتين، وحركتين أو أربعًا قبل الهمز.",
     ["sukūn (preferred)", "ṣilah: -mū"]),
    ("tasheel", "riwaya", "core", None, 93, "tasheel",
     "Tas-hīl (eased hamza)", "تسهيل الهمزة",
     "Qālūn eases this hamza between a hamza and the vowel letter of its ḥaraka. Learn it by listening.",
     "يُنطق بالهمز بينه وبين الحرف المجانس لحركته، ويُضبط بالمشافهة."),
    ("isqat", "riwaya", "core", None, 98, None,
     "Dropped first hamza", "إسقاط الهمزة الأولى",
     "Two hamzas with fatḥa meet across words: Qālūn drops the first. The long vowel before it: 2 (preferred) or 4.",
     "إذا اتفقت الهمزتان بالفتح من كلمتين أسقط قالون الأولى، مع جواز القصر وهو المقدم والتوسط.",
     ["2 (preferred)", "4"]),
    ("ibdal", "riwaya", "core", None, 101, None,
     "Hamza changed to a letter", "إبدال الهمزة",
     "Qālūn replaces this hamza with a vowel letter (alif, wāw or yāʾ).",
     "أبدل قالون الهمزة حرفًا من جنس حركة ما قبلها."),
    ("naql", "riwaya", "core", None, 102, None,
     "Naql (vowel moved)", "نقل حركة الهمزة",
     "Qālūn moves the hamza's vowel onto the sākin letter before it and drops the hamza.",
     "نقل قالون حركة الهمز إلى الساكن قبله وأسقط الهمز."),
    ("hadhf", "riwaya", "core", None, 102, None,
     "Hamza omitted", "حذف الهمزة",
     "Qālūn reads this word without its hamza.",
     "حذف قالون الهمزة من هذه الكلمة."),
    ("imala", "riwaya", "core", None, 110, None,
     "Imāla", "إمالة كبرى",
     "Qālūn tilts the ā toward ī here (هارٍ). It is his only major imāla.",
     "أمال قالون لفظ «هارٍ» بالتوبة إمالة كبرى وصلًا ووقفًا، ولا إمالة كبرى له في غيره."),
    ("taqlil", "riwaya", "core", None, 110, None,
     "Fatḥ or taqlīl", "الفتح والتقليل",
     "Qālūn reads التوراة with an open ā (preferred) or slightly tilted (taqlīl).",
     "لقالون في «التوراة» الفتح وهو المقدم والتقليل.", ["fatḥ (preferred)", "taqlīl"]),
    ("ishmam", "riwaya", "core", None, 106, None,
     "Ishmām", "إشمام",
     "Blend a trace of ḍamma into the vowel here, as taught orally.",
     "يُشمّ الحرف شيئًا من الضم، ويُؤخذ بالمشافهة."),
    ("ikhtilas", "riwaya", "core", None, 106, None,
     "Ikhtilās (snatched vowel)", "اختلاس الحركة",
     "Say this vowel quickly and lightly, about a third of its length.",
     "يُسرع بنطق الحركة حتى يذهب ثلثها."),
    ("ha_kinaya_qasr", "riwaya", "core", None, 88, None,
     "Pronoun hā without ṣilah", "قصر هاء الكناية",
     "One of the eight words where Qālūn reads the hā short, without ṣilah.",
     "من الكلمات الثماني التي رواها قالون بالقصر من غير صلة."),
    ("ha_kinaya_both", "riwaya", "core", None, 88, None,
     "Pronoun hā: two ways", "هاء الكناية بالوجهين",
     "Qālūn reads يأتِه short (preferred) or with ṣilah.",
     "روى قالون الهاء في «يأته» بطه بالقصر وهو المقدم والصلة.", ["short (preferred)", "ṣilah"]),
    ("ha_sukun", "riwaya", "core", None, None, None,
     "Sākin hā in وهْو / فهْي", "إسكان الهاء",
     "Qālūn reads the hā of هو / هي here with sukūn (وَهْوَ، فَهْيَ، لَهْوَ).",
     "قرأ قالون الهاء هنا ساكنة في «هو» و«هي» نحو: وَهْوَ، فَهْيَ، لَهْوَ."),
    ("ya_idafa", "riwaya", "core", None, 119, None,
     "Yāʾ of the speaker", "ياء الإضافة",
     "Qālūn's vowel on this yāʾ (open or sākin) differs from Ḥafṣ.",
     "لقالون في هذه الياء من الفتح أو الإسكان خلاف رواية حفص."),
    ("ya_zaida", "riwaya", "core", None, 122, None,
     "Extra yāʾ (zāʾidah)", "ياء زائدة",
     "Qālūn pronounces this yāʾ when joining and drops it when stopping.",
     "أثبت قالون هذه الياء وصلًا وحذفها وقفًا."),
    ("idgham_riwaya", "riwaya", "core", None, 104, None,
     "Qālūn's idghām / iẓhār choice", "الإظهار والإدغام لقالون",
     "A place where readers differ; follow Qālūn's choice shown in the note.",
     "موضع اختلف فيه القراء بين الإظهار والإدغام، والمتّبع هنا ما رواه قالون."),
    ("no_sakt", "riwaya", "core", None, None, None,
     "No sakt for Qālūn", "لا سكت لقالون",
     "Ḥafṣ makes a short pause here; Qālūn joins straight through.",
     "يسكت حفص هنا سكتة لطيفة، ولا سكت لقالون."),
    ("riwaya_diff", "riwaya", "core", None, 75, None,
     "Read differently from Ḥafṣ", "خلاف رواية حفص",
     "Qālūn reads this word differently from Ḥafṣ ʿan ʿĀṣim (see the note).",
     "يقرأ قالون هذه الكلمة بخلاف رواية حفص عن عاصم."),
]

RULES = {}
for row in _RULES:
    rid, group, level, harakat, page, tag, en, ar, explain_en, explain_ar = row[:10]
    RULES[rid] = {"group": group, "level": level, "harakat": harakat, "page": page, "tag": tag, "en": en, "ar": ar,
                  "explain_en": explain_en, "explain_ar": explain_ar, **({"wajh": row[10]} if len(row) > 10 else {})}

# Earlier rules win the colour when one letter carries several.
PRIORITY = {rid: i for i, rid in enumerate(
    ["madd_lazim", "madd_lazim_harfi", "madd_ayn", "madd_muttasil_waqf", "madd_muttasil", "madd_changed_hamza",
     "madd_munfasil", "tasheel", "isqat", "ibdal", "naql", "imala", "ishmam", "ikhtilas", "hadhf", "ya_zaida",
     "idgham_ghunna", "iqlab", "ikhfa", "ikhfa_shafawi", "idgham_shafawi", "ghunna", "idgham_no_ghunna", "idgham_harf",
     "madd_arid", "madd_lin", "madd_silah", "mim_jam", "ha_kinaya_qasr", "ha_kinaya_both", "ha_sukun", "ya_idafa",
     "taqlil", "idgham_riwaya", "no_sakt", "riwaya_diff", "qalqala", "qalqala_waqf", "hamzat_wasl", "idgham_shamsi",
     "silent", "wasl_drop", "ra_both", "ra_tafkhim", "lam_tafkhim", "madd_badal", "madd_iwad", "madd_tabii",
     "madd_harfi_tabii", "tafkhim_letter", "ra_tarqiq", "lam_tarqiq", "izhar_halqi", "izhar_mutlaq",
     "izhar_shafawi", "izhar_qamari"])}
assert set(PRIORITY) == set(RULES), set(PRIORITY) ^ set(RULES)

# Ghunna on a mīm and idghām into nūn/mīm are refined per letter in targets.py.
TAGS = {
    "n_ikhfa": {"en": "Ikhfāʾ of nūn", "ar": "إخفاء النون", "rules": ["ikhfa"],
                "fix_en": "Hide the nūn: no tongue contact, a nasal hum for 2 counts.", "fix_ar": "أخفِ النون دون أن يلمس اللسان مخرجها، مع غنة حركتين."},
    "m_ikhfa": {"en": "Lip ikhfāʾ / iqlāb", "ar": "الإخفاء الشفوي والإقلاب", "rules": ["iqlab", "ikhfa_shafawi"],
                "fix_en": "Close the lips lightly on a hidden mīm and hum for 2 counts before the bāʾ.", "fix_ar": "أطبق الشفتين على ميم مخفاة مع غنة حركتين قبل الباء."},
    "n_ghunna": {"en": "Ghunna of nūn", "ar": "غنة النون", "rules": ["ghunna", "idgham_ghunna"],
                 "fix_en": "Hold the doubled nūn's nasal sound for 2 counts.", "fix_ar": "أظهر غنة النون المشددة بمقدار حركتين."},
    "m_ghunna": {"en": "Ghunna of mīm", "ar": "غنة الميم", "rules": ["ghunna", "idgham_ghunna", "idgham_shafawi"],
                 "fix_en": "Hold the doubled mīm's nasal sound for 2 counts.", "fix_ar": "أظهر غنة الميم المشددة بمقدار حركتين."},
    "idgham_ghunna": {"en": "Idghām with ghunna (ي و)", "ar": "الإدغام الناقص في الياء والواو", "rules": ["idgham_ghunna"],
                      "fix_en": "Merge the nūn into the yāʾ/wāw but keep its nasal sound for 2 counts.", "fix_ar": "أدغم النون في الياء أو الواو مع بقاء الغنة حركتين."},
    "qalqala": {"en": "Qalqala", "ar": "القلقلة", "rules": ["qalqala", "qalqala_waqf"],
                "fix_en": "Let the sākin letter bounce with a short echo, without adding a vowel.", "fix_ar": "أظهر نبرة الحرف الساكن واهتزازه دون أن تحركه."},
    "mad": {"en": "Madd beyond 2 counts", "ar": "المد الزائد على حركتين", "rules": ["madd_lazim", "madd_lazim_harfi", "madd_ayn", "madd_muttasil", "madd_muttasil_waqf"],
            "fix_en": "Hold this long vowel longer: 4 counts for muttaṣil, 6 for lāzim.", "fix_ar": "أطل المد: أربع حركات في المتصل وست في اللازم."},
    "silah": {"en": "Ṣilah of the pronoun hā", "ar": "صلة هاء الكناية", "rules": ["madd_silah"],
              "fix_en": "Lengthen the hā to hū / hī for 2 counts when joining.", "fix_ar": "صِل الهاء بواو أو ياء لفظية بمقدار حركتين."},
    "tasheel": {"en": "Tas-hīl (Qālūn)", "ar": "التسهيل لقالون", "rules": ["tasheel"],
                "fix_en": "Ease this hamza between hamza and alif/yāʾ/wāw; do not say it fully as Ḥafṣ does.", "fix_ar": "سهّل الهمزة بين الهمزة والحرف المجانس لحركتها، ولا تحققها كحفص."},
}
MODEL_TAGS = sorted(TAGS)
assert {r["tag"] for r in RULES.values() if r["tag"]} <= set(TAGS)
