"""The riwāyah topics (مواضيع الرواية) of Qālūn, chapter 3 of the Awqaf book.

Each topic lists the engine rules whose occurrences illustrate it, so the web
page can show every place it happens in the muṣḥaf. `split` maps a rule to a
regex its English note must match (one rule can belong to several topics).
"""

TOPICS = [
    {"id": "istiadha", "page": 79, "rules": [],
     "en": "Seeking refuge (al-istiʿādhah)", "ar": "الاستعاذة",
     "summary_en": "Say أعوذ بالله من الشيطان الرجيم before reading. It is recommended, and it is not part of the Quran. Say it aloud, except in prayer, in private, or when joining a circle mid-reading.",
     "summary_ar": "يُستحب التعوذ قبل القراءة بصيغة «أعوذ بالله من الشيطان الرجيم»، وليس من القرآن. يُجهر به إلا في الصلاة والخلوة والقراءة سرًّا وفي حلقة لم يكن القارئ مبتدئها.",
     "points": [["Four ways with basmalah and a surah start: stop after each, join the last two, join the first two, or join all.",
                 "مع البسملة وأول السورة أربعة أوجه: قطع الجميع، قطع الأول ووصل الثاني بالثالث، وصل الأول بالثاني وقطع الثالث، ووصل الجميع."]]},
    {"id": "basmala", "page": 82, "rules": [],
     "en": "The basmalah", "ar": "البسملة",
     "summary_en": "Qālūn reads the basmalah between every two surahs, except before at-Tawbah. Between surahs you may stop after each part, stop then join the basmalah to the surah, or join everything. Never join the end of a surah to the basmalah and stop there.",
     "summary_ar": "أثبت قالون البسملة بين كل سورتين إلا قبل براءة. ولها بين السورتين ثلاثة أوجه جائزة: قطع الجميع، وقطع الأول ووصل الثاني بالثالث، ووصل الجميع، والممنوع وصل آخر السورة بالبسملة والوقف عليها.",
     "points": [["Between al-Anfāl and at-Tawbah: pause, a short sakt, or join, without basmalah.",
                 "بين الأنفال وبراءة: الوقف أو السكت أو الوصل، كلها بلا بسملة."]]},
    {"id": "mim_jam", "page": 85, "rules": ["mim_jam"],
     "en": "Mīm al-jamʿ", "ar": "ميم الجمع",
     "summary_en": "The plural mīm (عليهم، أنتم، لكم). Before a sākin letter Qālūn reads it with ḍamma and no ṣilah (عليكمُ الميتة). Before a voweled letter he has two ways: sukūn, which is preferred, or ṣilah with a pronounced wāw (عليهمُو).",
     "summary_ar": "ميم الجمع قبل الساكن تُضم بلا صلة. وقبل المتحرك لقالون وجهان: الإسكان وهو المقدم، والصلة بواو لفظية تُمد حركتين، أو حركتين وأربعًا إن كان بعدها همز.",
     "points": [["Recognise it by the letter before it: ت ك ه or ء (أنتم، عليكم، عليهم، هاؤم).", "علامتها أن يسبقها أحد حروف «أهتك»."]]},
    {"id": "ha_kinaya", "page": 87, "rules": ["madd_silah", "ha_kinaya_qasr", "ha_kinaya_both"],
     "en": "The pronoun hā (hāʾ al-kināyah)", "ar": "هاء الكناية",
     "summary_en": "The hā meaning 'him/his'. Between two voweled letters it gets ṣilah (لَهُو، بِهِي). Next to a sākin letter it stays short. Qālūn reads eight words short (يؤدِّه، نؤتِه، نولِّه، نصلِه، أرجِه، فألقِه، ويتقِه، يرضَه), reads يأتِه both ways, and reads يرَهُو with ṣilah.",
     "summary_ar": "تُوصل الهاء بين متحركين بواو أو ياء لفظية، ولا توصل في غير ذلك. روى قالون ثماني كلمات بالقصر، و«يأته» بطه بالوجهين، و«يره» بالصلة.",
     "points": [["Before a hamza the ṣilah becomes a separated madd: 2 or 4.", "إن وقعت بين متحركين ثانيهما همزة قطع فلقالون الصلة مع القصر والتوسط."],
                ["The hā of هٰذِهِ follows the same rule.", "تُلحق بها هاء «هذه»."]]},
    {"id": "madd", "page": 90, "rules": ["madd_muttasil", "madd_muttasil_waqf", "madd_munfasil", "madd_changed_hamza", "madd_badal"],
     "en": "Madd and qaṣr", "ar": "المد والقصر",
     "summary_en": "Connected madd: 4 counts (tawassuṭ); 4 or 6 when you stop on a final hamza. Separated madd: 2 or 4. This includes yā of calling, hā of attention, and ṣilah of hā or mīm before a hamza. Badal madd: 2 counts only.",
     "summary_ar": "المتصل: التوسط، وله التوسط والإشباع إن وُقف على الهمز المتطرف بالسكون. المنفصل بنوعيه الحقيقي والحكمي: القصر والتوسط. البدل: القصر فحسب.",
     "points": [["When two causes meet, the stronger wins: lāzim, then muttaṣil, then ʿāriḍ, then munfaṣil, then badal.", "إذا اجتمع سببان عُمل بأقواهما: اللازم فالمتصل فالعارض فالمنفصل فالبدل."]]},
    {"id": "hamzatan_kalima", "page": 93, "rules": ["tasheel"], "split": {"tasheel": "one word|without idkh|أرأيت|أئمة"},
     "en": "Two hamzas in one word", "ar": "الهمزتان من كلمة",
     "summary_en": "Qālūn eases the second hamza (tas-hīl) and puts an alif between the two (idkhāl): ءَا۬نذرتهم. There is no idkhāl in أئمّة، ءامنتم (3 places) and ءالهتنا. أشهدوا has both ways, idkhāl preferred.",
     "summary_ar": "لقالون تسهيل الثانية مع إدخال ألف بينهما، واستُثني من الإدخال «أئمة» و«ءامنتم» في مواضعها الثلاثة و«ءالهتنا»، وله في «أشهدوا» الوجهان والإدخال مقدم.",
     "points": [["أرأيت after the question hamza: the hamza is eased.", "يُسهّل الهمزة في «أرأيت» المسبوقة بهمزة الاستفهام."],
                ["Repeated questions (11 places): question in the first, statement in the second, reversed in an-Naml and al-ʿAnkabūt.", "الاستفهام المكرر: يستفهم في الأول ويخبر في الثاني، ويعكس في النمل والعنكبوت."]]},
    {"id": "hamzatan_kalimatayn", "page": 98, "rules": ["isqat", "tasheel", "ibdal", "madd_changed_hamza"],
     "split": {"tasheel": "across words|meeting", "ibdal": "^Second hamza"},
     "en": "Two hamzas across two words", "ar": "الهمزتان من كلمتين",
     "summary_en": "Same vowel: two fatḥas drop the first hamza (جا أمرنا); two kasras or two ḍammas ease the first (هؤلاءِ إن). Different vowels: fatḥa then kasra/ḍamma eases the second; kasra then fatḥa turns it into yāʾ; ḍamma then fatḥa turns it into wāw; ḍamma then kasra turns it into wāw (preferred) or eases it.",
     "summary_ar": "المتفقتان: إسقاط الأولى في المفتوحتين، وتسهيل الأولى في المكسورتين والمضمومتين. المختلفتان: تسهيل الثانية في المفتوحة فالمكسورة أو المضمومة، وإبدالها ياء بعد كسر، وواوًا بعد ضم، ولها في المضمومة فالمكسورة الإبدال وهو المقدم والتسهيل.",
     "points": [["بالسوءِ إلا (Yūsuf): wāw doubled (preferred) or eased. النبيءِ إن / النبيءِ إلا (al-Aḥzāb): yāʾ doubled only.", "«بالسوء إلا» بالإبدال مع الإدغام وهو المقدم والتسهيل، و«للنبيء إن» و«النبيء إلا» بالإبدال مع الإدغام فقط."],
                ["When you stop on the first word, both hamzas are pronounced fully.", "إذا وُقف على الأولى رجعتا إلى التحقيق."]]},
    {"id": "hamz_mufrad", "page": 101, "rules": ["ibdal", "hadhf", "naql"], "split": {"ibdal": "^Qālūn"},
     "en": "The single hamza", "ar": "الهمز المفرد",
     "summary_en": "Qālūn pronounces the hamza fully except in a few words. It becomes a letter in ياجوج، ماجوج، مؤصدة، بيس (al-Aʿrāf), وريًّا، منساته and سال, and optionally in لأهب. It is eased in ها أنتم and dropped in الصابين، الصابون، يضاهون. Its vowel moves to the letter before in ءالآن (Yūnus), ردًا and عادًا الُولى.",
     "summary_ar": "الأصل عند قالون التحقيق، إلا: الإبدال في «ياجوج وماجوج، مؤصدة، بئيس بالأعراف، رئيا، منسأته، سأل»، وفي «لأهب» بخلف، والتسهيل في «ها أنتم»، والحذف في «الصابئين، الصابئون، يضاهئون»، والنقل في «ءالآن» بيونس و«ردءا» و«عادًا الأولى».",
     "points": []},
    {"id": "idgham", "page": 104, "rules": ["idgham_riwaya", "no_sakt"],
     "en": "Iẓhār and idghām", "ar": "الإظهار والإدغام",
     "summary_en": "Qālūn keeps clear the ذال of إذ, the دال of قد, the feminine تاء and the لام of هل/بل wherever readers differ. He merges ذ into ت in أخذتم/اتخذتم, ب into م in يعذبْ مَن (al-Baqarah), and the nūn of sīn in طسم. يلهث ذلك and اركب معنا have both ways, idghām preferred. لبثت and يس والقرآن / ن والقلم stay clear. Major idghām only in مكّني and تأمنّا (ikhtilās preferred).",
     "summary_ar": "أظهر قالون ذال إذ ودال قد وتاء التأنيث ولام هل وبل عند حروفها المختلف فيها، وأدغم الذال في التاء في «أخذتم» وبابه، والباء في الميم في «ويعذب من» بالبقرة، ونون «سين» في الميم في «طسم»، وله الوجهان في «يلهث ذلك» و«اركب معنا» والإدغام مقدم، وأظهر «لبثت» و«يس والقرآن» و«ن والقلم».",
     "points": [["Qālūn has no sakt: عوجًا قيمًا، مرقدنا هذا، مَن راق، بل ران are read straight through.", "لا سكت لقالون في «عوجا» و«مرقدنا» و«من راق» و«بل ران»."]]},
    {"id": "imala", "page": 109, "rules": ["imala", "taqlil"],
     "en": "Fatḥ and imāla", "ar": "الفتح والإمالة",
     "summary_en": "Qālūn reads almost everything with an open ā. His only major imāla is هارٍ (at-Tawbah). التوراة has an open ā (preferred) or taqlīl. He has only fatḥ in كهيعص (Maryam).",
     "summary_ar": "قالون من المقلّين، لم يمل إلا «هار» بالتوبة إمالة كبرى، وله في «التوراة» الفتح وهو المقدم والتقليل، وليس له في «ها» و«يا» من فاتحة مريم إلا الفتح.",
     "points": []},
    {"id": "waqf_awakhir", "page": 112, "rules": ["qalqala_waqf", "madd_arid"],
     "en": "Stopping on word endings", "ar": "الوقف على أواخر الكلم",
     "summary_en": "Stop with sukūn by default. Rawm (a faint trace of the vowel) is allowed on ḍamma and kasra. Ishmām (rounding the lips, no sound) is allowed on ḍamma only. Neither is used on fatḥa, on hāʾ al-taʾnīth, or on mīm al-jamʿ.",
     "summary_ar": "الأصل في الوقف السكون، ويدخل الروم المضموم والمكسور، والإشمام المضموم فقط، ولا يدخلان المفتوح ولا هاء التأنيث ولا ميم الجمع ولا عارض الشكل.",
     "points": [["Before a final sākin after a long vowel: 2, 4 or 6 counts; with rawm only 2.", "في العارض للسكون القصر والتوسط والإشباع، ومع الروم القصر."]]},
    {"id": "waqf_rasm", "page": 116, "rules": [],
     "en": "Stopping as the muṣḥaf is written", "ar": "الوقف على مرسوم الخط",
     "summary_en": "Qālūn follows the Uthmānī spelling when he stops. He stops with tāʾ on رحمت / نعمت written with an open tāʾ, and on يا أبت، هيهات، مرضات، اللات، ذات، لات. He stops on the lām of مالِ, on the nūn of كأيّن, and on أيُّه without alif.",
     "summary_ar": "يقف قالون متبعًا الرسم: بالتاء على ما رُسم بالتاء المبسوطة، وعلى «يا أبت» و«هيهات» و«مرضات» و«اللات» و«ذات» و«لات»، وعلى اللام في «مال»، وبالنون في «كأين»، وعلى «أيه» بلا ألف.",
     "points": []},
    {"id": "ya_idafa", "page": 119, "rules": ["ya_idafa"],
     "en": "Yāʾāt al-iḍāfah", "ar": "ياءات الإضافة",
     "summary_en": "The 'my/me' yāʾ. Qālūn opens it before most hamzas, with listed exceptions. He opens it before al- and before a waṣl hamza, except three places. Before other letters he usually keeps it sākin, opening only seven, such as بيتيَ، وجهيَ، مماتيَ، وليَ دين.",
     "summary_ar": "فتح قالون ياء الإضافة قبل همز القطع المفتوح والمكسور والمضموم إلا مواضع مخصوصة، وقبل همزة الوصل مع لام التعريف مطلقًا، ودونها إلا ثلاثة مواضع، وأسكنها قبل سائر الحروف إلا سبعًا.",
     "points": []},
    {"id": "ya_zaida", "page": 122, "rules": ["ya_zaida"],
     "en": "Extra yāʾs (az-zawāʾid)", "ar": "الياءات الزوائد",
     "summary_en": "Yāʾs missing from the written text: Qālūn pronounces them when joining and drops them when stopping (اتبعنِ، الداعِ، أكرمنِ). In الداعِ إذا دعانِ (al-Baqarah) dropping them is preferred.",
     "summary_ar": "أثبت قالون الياءات الزوائد وصلًا وحذفها وقفًا، وله في «الداع» و«دعان» بالبقرة الوجهان والحذف مقدم.",
     "points": []},
    {"id": "farsh", "page": None, "rules": ["riwaya_diff", "ha_sukun", "ishmam", "ikhtilas"],
     "en": "Words Qālūn reads differently from Ḥafṣ", "ar": "كلمات خالف فيها قالون حفصًا",
     "summary_en": "Individual words where the two riwāyahs differ, such as مَلِكِ، يُخادعون، يُكذّبون، وَهْوَ، النبيء. The engine finds them by aligning the Qālūn and Ḥafṣ texts word by word.",
     "summary_ar": "كلمات فرشية يختلف فيها قالون عن حفص، استُخرجت بمقابلة نص الروايتين كلمة كلمة.",
     "points": []},
]
